name = "World Gen"
author = "sweenu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "876cec8e96ca8c41860f90c2e946fdcbee25afd64526fa002f6f40676df81c26"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
