name = "World Gen"
author = "sweenu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e09ea9d04fec21355cc4daeadd5b6d74eadb59ac253ace4c758ef01591b376b0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
