name = "Utilities"
author = "sweenu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cb80e2e4cdbe6323ed3507dda27bd7dcbbfe4802530b72c9955bc05b65cfbe22"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
