name = "Utilities"
author = "sweenu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9249f820c8fb6a585797a85057a3e8d55442d648c64657fc402939d15b240d34"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
