name = "Utilities"
author = "sweenu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5c60cbec80436aa88315f91cae8146aa05a36f36b750aa86e9731508d0bb3a85"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
