name = "Utilities"
author = "sweenu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "09a2be7bb2f210e31de3bea4ce19f891f0d3afc534412ecfb37f61e19899dd69"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
