name = "Cobblemon"
author = "sweenu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1d74132e54c4a79187bafaeb00bf1e641c3b01bce18c67fe11e136c51194cf05"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
