name = "Optimization"
author = "sweenu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc1c4a7562f008ac679f4a0b4598f9a976bc191089e0afcc6716e7e4881f19e5"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
