name = "Decoration"
author = "sweenu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "32999720e9ff8f81429cb0a096d152f6c67b29e120966b4f671af94abce5cd22"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
