name = "Create"
author = "sweenu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "23e9e286ddcd67df77ea79ef55c0a097c1e65f3da026bf57aa008d80944af193"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
